### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by bsab** [testdrivenio/fastapi-jwt#4]
Hi, i'm trying to install all the dependencies usign pip but the requirements.txt is missing

**Comment by amalshaji** [comment]
```bash
email-validator==1.1.2
fastapi==0.62.0
PyJWT==1.7.1
python-decouple==3.3
uvicorn==0.12.3
```

**Comment by mjhea0** [comment]
Just added it to the repo. Thanks, @amalshaji!

https://github.com/testdrivenio/fastapi-jwt/commit/e1de9c5aaed0342b2cc4639eab7674d27b07001d
